/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nehemie_mutuelle;

import com.google.i18n.phonenumbers.NumberParseException;
import com.google.i18n.phonenumbers.PhoneNumberUtil;
import com.google.i18n.phonenumbers.Phonenumber;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultFormatter;
import javax.swing.text.DocumentFilter;
import org.apache.commons.lang.WordUtils;

/**
 *
 * @author elommarcarnold
 */
public class Adhesion_persmor extends javax.swing.JFrame {
    Connection connect=null;
    PreparedStatement pst=null;
    Connect conn=new Connect();
    private main main;
    private DecimalFormatSymbols dfs;
    private DecimalFormat dFormat;
    boolean res1;
    boolean res2;
    
 class RegexFormatter extends DefaultFormatter {
  private Pattern pattern;

  private Matcher matcher;

  public RegexFormatter() {
    super();
  }

  /**
   * Creates a regular expression based AbstractFormatter.
   * pattern specifies the regular expression that will be used
   * to determine if a value is legal.
   */
  public RegexFormatter(String pattern) throws PatternSyntaxException {
    this();
    setPattern(Pattern.compile(pattern));
  }

  /**
   * Creates a regular expression based AbstractFormatter.
   * pattern specifies the regular expression that will be used
   * to determine if a value is legal.
   */
  public RegexFormatter(Pattern pattern) {
    this();
    setPattern(pattern);
  }

  /**
   * Sets the pattern that will be used to determine if a value is legal.
   */
  public void setPattern(Pattern pattern) {
    this.pattern = pattern;
  }

  /**
   * Returns the Pattern used to determine if a value is legal.
   */
  public Pattern getPattern() {
    return pattern;
  }

  /**
   * Sets the Matcher used in the most recent test if a value is
   * legal.
   */
  protected void setMatcher(Matcher matcher) {
    this.matcher = matcher;
  }

  /**
   * Returns the Matcher from the most test.
   */
  protected Matcher getMatcher() {
    return matcher;
  }

  /**
   * Parses text returning an arbitrary Object. Some formatters
   * may return null.
   * 
   * If a Pattern has been specified and the text completely
   * matches the regular expression this will invoke setMatcher.
   * 
   * @throws ParseException
   *           if there is an error in the conversion
   * @param text
   *          String to convert
   * @return Object representation of text
   */
  public Object stringToValue(String text) throws ParseException {
    Pattern pattern = getPattern();

    if (pattern != null) {
      Matcher matcher = pattern.matcher(text);

      if (matcher.matches()) {
        setMatcher(matcher);
        return super.stringToValue(text);
      }
      throw new ParseException("Pattern did not match", 0);
    }
    return text;
  }
}

    /**
     * Creates new form Adhesion_persmor
     */
    class UppercaseDocumentFilter extends DocumentFilter {
    public void insertString(DocumentFilter.FilterBypass fb, int offset,
            String text, AttributeSet attr) throws BadLocationException {

        fb.insertString(offset, text.toUpperCase(), attr);
    }

    public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
            String text, AttributeSet attrs) throws BadLocationException {

        fb.replace(offset, length, text.toUpperCase(), attrs);
    }
  }
    
    public Adhesion_persmor(main mn) {
        initComponents();
        this.main=mn;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        demoDateField1 = new com.jp.samples.comp.calendarnew.DemoDateField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        dfs = new DecimalFormatSymbols();
        dfs.setDecimalSeparator('.');
        dfs.setGroupingSeparator(',');
        dFormat= new DecimalFormat("#0.##", dfs);
        jFormattedTextField1 = new javax.swing.JFormattedTextField(dFormat);
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        demoDateField2 = new com.jp.samples.comp.calendarnew.DemoDateField();
        demoDateField3 = new com.jp.samples.comp.calendarnew.DemoDateField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Raison Sociale");

        DocumentFilter filter = new UppercaseDocumentFilter();
        ((AbstractDocument) jTextField1.getDocument()).setDocumentFilter(filter);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel2.setText("Date de création");

        jLabel3.setText("Activité principale");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel4.setText("Adresse");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel5.setText("Num COE");

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jLabel12.setText("Lieu de création");

        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });

        demoDateField1.setYearDigitsAmount(4);

        jLabel6.setText("Personne de référence");

        ((AbstractDocument) jTextField5.getDocument()).setDocumentFilter(filter);
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel15.setText("Nom");

        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jLabel16.setText("Prénoms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(demoDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15)
                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jTextField12)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(demoDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setText("Téléphone");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "National ", "International" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField2FocusLost(evt);
            }
        });

        jLabel17.setText("");

        jLabel14.setText("Type adhésion");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Epargne ", "Tontine", "Epargne & Tontine" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Versements initiaux");

        jLabel8.setText("Droit d'adhésion");

        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                performSummation(null);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                performSummation(null);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        };

        DocumentFilter numericFilter = new DocumentFilter(){

            //   @Override
            //  public void insertString(FilterBypass fb, int offset,
                //          String string, AttributeSet attr)
            //          throws BadLocationException {
                //      fb.insertString(offset, string.replaceAll("[^\\d]", ""), attr);
                //  }

            //   @Override
            //   public void replace(FilterBypass fb, int offset, int length,
                //           String text, AttributeSet attrs)
            //          throws BadLocationException {

                //      fb.replace(offset, length, text.replaceAll("[^\\d]", ""), attrs);
                //   }
            @Override
            public void insertString(FilterBypass fb, int offset, String text,
                AttributeSet attr) throws BadLocationException {
                super.insertString(fb, offset, revise(text), attr);
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text,
                AttributeSet attrs) throws BadLocationException {
                super.replace(fb, offset, length, revise(text), attrs);
            }

            private String revise(String text) {
                StringBuilder builder = new StringBuilder(text);
                int index = 0;
                while (index < builder.length()) {
                    if (accept(builder.charAt(index))) {
                        index++;
                    } else {
                        // Don't increment index here, or you'll skip the next character!
                        builder.deleteCharAt(index);
                    }
                }
                return builder.toString();
            }

            /**
            * Determine if the character should remain in the String. You may
            * override this to get any matching criteria you want.
            * @param c The character in question
            * @return true if it's valid, false if it should be removed.
            */
            public boolean accept(final char c) {
                return Character.isDigit(c) || c == ' ';
            }
        };
        ((AbstractDocument) jTextField6.getDocument()).setDocumentFilter(numericFilter);
        ((AbstractDocument) jTextField7.getDocument()).setDocumentFilter(numericFilter);
        ((AbstractDocument) jTextField8.getDocument()).setDocumentFilter(numericFilter);

        jTextField6.getDocument().addDocumentListener(documentListener);
        jTextField7.getDocument().addDocumentListener(documentListener);
        jTextField8.getDocument().addDocumentListener(documentListener);
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jLabel9.setText("Part Sociale");

        jFormattedTextField4.setEnabled(false);

        jLabel10.setText("Dépôt");

        jLabel11.setText("TOTAL");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jFormattedTextField1.setVisible(false);

        jLabel18.setText("N° Carnet");

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        //jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new RegexFormatter("\\(\\d{3}\\)\\d{3}-\\d{4}")));

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Date d'adhésion:");

        jLabel20.setText("Epargne");

        jLabel21.setText("Tontine");

        demoDateField3.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(jLabel17))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFormattedTextField4)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(demoDateField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(demoDateField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))
                            .addComponent(demoDateField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(demoDateField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(468, 468, 468))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private static boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e){
            return false;
        }
    }
     
     private void performSummation(java.awt.event.ActionEvent evt) {
         //int total =0;
         double total = 0;
        if(jTextField6.getText().trim().length() > 0){
            try{
  //              total += Integer.parseInt(jTextField6.getText());
                total += Double.parseDouble(jTextField6.getText());
            }catch(NumberFormatException nbx){
            }
        }

        if(jTextField7.getText().trim().length() > 0){
            try{
             //   total += Integer.parseInt(jTextField7.getText());
                total += Double.parseDouble(jTextField7.getText());
            }catch(NumberFormatException nbx){
            }
        }
        
        if(jTextField8.getText().trim().length() > 0){
            try{
               // total += Integer.parseInt(jTextField8.getText());
                total += Double.parseDouble(jTextField8.getText());
            }catch(NumberFormatException nbx){
            }
        }

          //  jTextField9.setText(new BigDecimal(total.toString()).stripTrailingZeros().toPlainString());
          jTextField9.setText(String.format("%.0f\n",total));
//        jTextField9.setText(""+total);

    }
     
          private boolean verifynumcarn(int i) throws SQLException {
        String sql0="";
         if (i==0) sql0="SELECT Num_carnet FROM Profil_adulte WHERE Type_adhesion='"+"Epargne"+"' UNION SELECT LEFT(Num_carnet,4) FROM Profil_adulte WHERE Type_adhesion='"+"Epargne et tontine"+"'" + " UNION " +"SELECT Num_carnet FROM Profil_enfant WHERE Type_adhesion='"+"Epargne"+"' UNION SELECT LEFT(Num_carnet,4) FROM Profil_enfant WHERE Type_adhesion='"+"Epargne et tontine"+"'" + " UNION "+ "SELECT Num_carnet FROM Profil_persmorale WHERE Type_adhesion='"+"Epargne"+"' UNION SELECT LEFT(Num_carnet,4) FROM Profil_persmorale WHERE Type_adhesion='"+"Epargne et tontine"+"'";
        // else sql0="SELECT Num_carnet FROM Profil_adulte WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_adulte WHERE Type_adhesion='"+"Epargne et tontine"+"'";
         else sql0="SELECT Num_carnet FROM Profil_adulte WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_adulte WHERE Type_adhesion='"+"Epargne et tontine"+"'" + " UNION " +"SELECT Num_carnet FROM Profil_enfant WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_enfant WHERE Type_adhesion='"+"Epargne et tontine"+"'" + " UNION "+ "SELECT Num_carnet FROM Profil_persmorale WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_persmorale WHERE Type_adhesion='"+"Epargne et tontine"+"'";
    
            // Vérifier numero carnet 
            connect=Connect.ConnectDb();
            Statement stmt = null;
            ResultSet rs = null;
              System.out.println("sql0"+sql0);
            
              try {
                  stmt= connect.createStatement();
                  rs=stmt.executeQuery(sql0);
                  if(i==0) {  // compare tontine
                while (rs.next()) {
                     if(jFormattedTextField3.getText().equalsIgnoreCase(rs.getString(1))) return true;
                  }
                 } else {
                       while (rs.next()) {
                     if(jFormattedTextField4.getText().equalsIgnoreCase(rs.getString(1))) return true;
                  }
                  }
                
                  
                  //    JOptionPane.showMessageDialog( this, "hostel name already exists","Error", JOptionPane.ERROR_MESSAGE);
                  //      y3.setText("");
                  //      y3.requestDefaultFocus();
                  //     return;
              } catch (SQLException ex) {
                  Logger.getLogger(Adhesion_adulte.class.getName()).log(Level.SEVERE, null, ex);
              }
              
              connect.close();
              stmt.close();
              rs.close();
            return false;
    }
          
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Validate carnet num
      
        if(jComboBox1.getSelectedIndex()==0 || jComboBox1.getSelectedIndex()==2) {
        try {
                  res1 = verifynumcarn(0);
                 
             } catch (SQLException ex) {
                 Logger.getLogger(Adhesion_enfant.class.getName()).log(Level.SEVERE, null, ex);
             }
        } else if (jComboBox1.getSelectedIndex()==1 || jComboBox1.getSelectedIndex()==2) {
         try {
                  res2 = verifynumcarn(1);
               
             } catch (SQLException ex) {
                 Logger.getLogger(Adhesion_enfant.class.getName()).log(Level.SEVERE, null, ex);
             }
         
           
        }
        System.out.println("res1"+res1+"res2"+res2);
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ raison sociale");
//        } else if(jFormattedTextField1.getText().equalsIgnoreCase("dd/MM/yyyy")){
//             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ date de création");
//        } else if(demoDateField1.getDate()==null){
//            JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ date de création");
//       } else if(jTextField11.getText().isEmpty()){
//             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ lieu de création");
        } else if(jTextField2.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ activité principale");
//        } else if(jTextField3.getText().isEmpty()){
//             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ adresse");
//        } else if(jTextField4.getText().isEmpty()){
//             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ numéro COE");
        } else if(jTextField5.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ nom personne de référence");
        } else if(jTextField12.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ prénom personne de référence");
        }
        
        else if(jFormattedTextField2.getText().equalsIgnoreCase("  -  -  -  ") || jFormattedTextField2.getText().equalsIgnoreCase("+") ){
             JOptionPane.showMessageDialog(this, "Veuillez renseigner le champ téléphone");
        } else if (jTextField6.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez renseigner les droits d'adhésion ");
           
//        } else if (!isDouble(jTextField6.getText())){
//            JOptionPane.showMessageDialog(this, "Les droits d'adhésion doivent être des chiffres");
//        } else if (!isDouble(jTextField7.getText())){
//            JOptionPane.showMessageDialog(this, "La part sociale doit être des chiffres");
//        } else if (!isDouble(jTextField8.getText())){
//            JOptionPane.showMessageDialog(this, "Le dépôt initial doit être des chiffres");
//        }else if (jTextField7.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Veuillez renseigner la part sociale ");
        } else if (jFormattedTextField3.getText().equalsIgnoreCase("0000") || jFormattedTextField4.getText().equalsIgnoreCase("0000")) { 
            
         JOptionPane.showMessageDialog(this, "Numéro de carnet 0000 invalide");
        } else if (jComboBox1.getSelectedIndex()==0 && jFormattedTextField3.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Numéro de carnet Epargne invalide");   
        }else if (jComboBox1.getSelectedIndex()==1 && jFormattedTextField4.getText().isEmpty()) { 
           JOptionPane.showMessageDialog(this, "Numéro de carnet Tontine invalide");   
        } else if (jComboBox1.getSelectedIndex()==2 && (jFormattedTextField3.getText().isEmpty() || jFormattedTextField4.getText().isEmpty())){
           JOptionPane.showMessageDialog(this, "Numéro de carnet invalide"); 
        } else if(jComboBox1.getSelectedIndex()==0 && res1==true) {
           JOptionPane.showMessageDialog(this, "Ce numéro carnet épargne est déjà utilisé");  
        }else if(jComboBox1.getSelectedIndex()==1 && res2==true) {    
            JOptionPane.showMessageDialog(this, "Ce numéro carnet tontine est déjà utilisé"); 
        } else if(jComboBox1.getSelectedIndex()==2 && res1==true) {    
            JOptionPane.showMessageDialog(this, "Ce numéro carnet épargne est déjà utilisé"); 
        } else if(jComboBox1.getSelectedIndex()==2 && res2==true) {    
            JOptionPane.showMessageDialog(this, "Ce numéro carnet tontine est déjà utilisé"); 
        }  else if (demoDateField2.getDate()==null && (jComboBox1.getSelectedIndex()==0 ||  jComboBox1.getSelectedIndex()==2)) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner la date d'adhésion Epargne"); 
        } else if (demoDateField3.getDate()==null && (jComboBox1.getSelectedIndex()==1 ||  jComboBox1.getSelectedIndex()==2)) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner la date d'adhésion Tontine"); 
        } else { 
            boolean success= true;
            String sql01="SELECT idProfil_persmorale FROM Profil_persmorale WHERE Raison_sociale= '" + jTextField1.getText() +"'";
             Statement stmt = null;
             boolean inserted=false;
            ResultSet rs2=null;
             connect=Connect.ConnectDb();
             try {
                   stmt= connect.createStatement();
                   rs2=stmt.executeQuery(sql01);
              } catch (SQLException ex) {
                  Logger.getLogger(Adhesion_enfant.class.getName()).log(Level.SEVERE, null, ex);
              }
              try {
                if (rs2.next() ){
                    JOptionPane.showMessageDialog(null, "Attention la personne morale indiquée est déjà enregistré");
                    success=false;
                    inserted=true;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Adhesion_adulte.class.getName()).log(Level.SEVERE, null, ex);
            }
              
             if (! inserted) {
                 
              String numcarn="";
                           if(jComboBox1.getSelectedIndex()==0) {
                               numcarn=jFormattedTextField3.getText();
                           } else if (jComboBox1.getSelectedIndex()==1){
                               numcarn=jFormattedTextField4.getText();
                           } else {
                                numcarn=jFormattedTextField3.getText() +"-"+jFormattedTextField4.getText();
                           }
            
            int partsociale=0;
            if(!jTextField7.getText().isEmpty())
                partsociale=Integer.parseInt(jTextField7.getText());
             
    //         String datecrea2=jFormattedTextField1.getText();
    //       sqlDate=new java.sql.Date(demoDateField1.getDate().getTime());
             java.sql.Date sqlDate=null;
            java.sql.Date sqlDate2=null;
            java.sql.Date sqlDate3=null;
            if (demoDateField1.getDate()!=null) sqlDate=new java.sql.Date(demoDateField1.getDate().getTime());
            if (demoDateField2.getDate()!=null)  sqlDate2=new java.sql.Date(demoDateField2.getDate().getTime());
            if (demoDateField3.getDate()!=null) sqlDate3=new java.sql.Date(demoDateField3.getDate().getTime());
//             DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
//            try {
//                datecrea= formatter.parse(datecrea2);
//                sqlDate= new java.sql.Date(datecrea.getTime());
//            } catch (ParseException ex) {
//                Logger.getLogger(Adhesion_persmor.class.getName()).log(Level.SEVERE, null, ex);
//                success=false;
//            }
             // On vérifie si la personne morale n'existe pas déjà 
             
             String fullname= jTextField5.getText()+ " "+ jTextField12.getText();
             String sql = "INSERT INTO Profil_persmorale " + 
                     "VALUES ("+ null +", '"+ jTextField1.getText(); 
             
             if (sqlDate==null){
                 sql=sql+"', null, '"+jTextField11.getText()+"', '"+jTextField2.getText()+"', '"+jTextField3.getText()+"', '"+jTextField4.getText()+"', '"+fullname+"', '"+jFormattedTextField2.getText()+"', '"+String.valueOf(jComboBox1.getSelectedItem()).trim()+"', '"+numcarn+"', '"+Integer.valueOf(jTextField6.getText().replace(" ", ""))+"', '"+partsociale;
            } else if (sqlDate !=null) {
                  sql=sql+"', '"+sqlDate +"', '"+jTextField11.getText()+"', '"+jTextField2.getText()+
                     "', '"+jTextField3.getText()+"', '"+jTextField4.getText()+"', '"+fullname+"', '"+jFormattedTextField2.getText()+"', '"+String.valueOf(jComboBox1.getSelectedItem()).trim()+"', '"+numcarn+"', '"+Integer.valueOf(jTextField6.getText().replace(" ", ""))+"', '"+partsociale;   
            } 
             
             if (sqlDate2==null){
                         sql=sql+"', null,";
                     } else if (sqlDate2!=null){
                          sql=sql+"','"+sqlDate2+"',";
                     } 
                     
                     if (sqlDate3==null){ 
                         sql=sql+"null"+", 1);";
                     } else if (sqlDate3!=null){   
                         sql=sql+"'"+sqlDate3+"',1);";
                     }              
             
               
                System.out.println(sql);
                int generatdkey = 0;

            try {  
                pst=connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            } catch (SQLException ex) {
                Logger.getLogger(Adhesion_persmor.class.getName()).log(Level.SEVERE, null, ex);
                success=false;
            }
            try {
                
                pst.execute();
                ResultSet rst= pst.getGeneratedKeys();
                generatdkey=0;
                if(rst.next()){
                    generatdkey= rst.getInt(1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Adhesion_persmor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erreur d'enregistrement");
                success=false;
            
            }
             if(!jTextField8.getText().isEmpty() && jTextField8.isEnabled()) {
                             java.util.Date dt = new java.util.Date();
                 java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                 String currentTime = sdf.format(dt);
                            String sql002 = "INSERT INTO Epargne VALUES ("+null+", '"+ currentTime + "', '"+"Dépot initial"+"', '"+jTextField8.getText()+"', '"+generatdkey+"', '"+"Pers Morale"+"');";
                try {                  
                    pst=connect.prepareStatement(sql002);
                    pst.execute();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erreur d'enregistrement du dépot initial");
                    Logger.getLogger(Adhesion_persmor.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
                try {
                    pst.close();
                    connect.close();
                    if (rs2!=null) rs2.close();
                    if (stmt!=null) stmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Adhesion_persmor.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            
            }
             
            if (success) {
            JOptionPane.showMessageDialog(null, "Enregistrement effectué avec succès");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            demoDateField1.setDate(null);
            demoDateField2.setDate(null);
            demoDateField3.setDate(null);
            jFormattedTextField3.setText("");
            jFormattedTextField4.setText("");
            jComboBox2.setSelectedIndex(0);
             jFormattedTextField2.setText("");
           // jFormattedTextField1.setText("dd/MM/yyyy");
            jTextField5.setText("");
            jTextField12.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
         //   jTextField10.setText("(+IND-)NN-NN-NN-NN");
            jTextField11.setText("");
            this.main.refresh();

                    }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText().trim());
        jTextField1.setText(jTextField1.getText().replaceAll("\\s+", " "));
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        jTextField11.setText(jTextField11.getText().trim());
        jTextField11.setText(jTextField11.getText().replaceAll("\\s+", " "));
        jTextField11.setText(WordUtils.capitalizeFully(jTextField11.getText()));
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText().trim());
        jTextField2.setText(jTextField2.getText().replaceAll("\\s+", " "));
        jTextField2.setText(jTextField2.getText().substring(0,1)+jTextField2.getText().substring(1));
        
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        jTextField3.setText(jTextField3.getText().trim());
        jTextField3.setText(jTextField3.getText().replaceAll("\\s+", " "));
        jTextField3.setText(WordUtils.capitalizeFully(jTextField3.getText()));
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        jTextField6.setText(jTextField6.getText().trim());
        jTextField6.setText(jTextField6.getText().replaceAll("\\s+", ""));
        
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
         jTextField5.setText(jTextField5.getText().trim());
        jTextField5.setText(jTextField5.getText().replaceAll("\\s+", " "));
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here:
          jTextField12.setText(jTextField12.getText().trim());
          jTextField12.setText(jTextField12.getText().replaceAll("\\s+", " "));
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        // TODO add your handling code here:
        if (!(Character.isAlphabetic(evt.getKeyChar()) || evt.getKeyChar() == '-' ) && !Character.isSpaceChar(evt.getKeyChar())) {
        evt.consume();
    } else if (jTextField12.getText().trim().length() == 0 ) {            //&& Character.isLowerCase(evt.getKeyChar())
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }else if(jTextField12.getText().endsWith(" ") ){
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }else{
         evt.setKeyChar(Character.toLowerCase(evt.getKeyChar()));
    }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
           if (jComboBox2.getSelectedIndex()==0){
             try {
                 System.out.println(jFormattedTextField2.getDocument());
          jFormattedTextField2.setDocument(new javax.swing.text.PlainDocument());       
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##-##")));
                } catch (java.text.ParseException ex) {
                 ex.printStackTrace();
                
         }
        }else {
       
          System.out.println(jFormattedTextField2.getDocument());
           jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory());  
          
           jFormattedTextField2.setDocument(new PhoneDocument());
            jFormattedTextField2.setText("+");
            
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jFormattedTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField2FocusGained
        // TODO add your handling code here:
          jLabel17.setText("");
        
        if (jComboBox2.getSelectedIndex()==1) {
           
              
             if (jFormattedTextField2.getText().equalsIgnoreCase("+")){
                
                    jFormattedTextField2.setDocument(new PhoneDocument());
                  jFormattedTextField2.setText("+");
             } else {
                 String before =jFormattedTextField2.getText();
                 before=before.replaceAll("\\s", "");
                 jFormattedTextField2.setText(before);
                 
             }
        }
    }//GEN-LAST:event_jFormattedTextField2FocusGained

    private void jFormattedTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField2FocusLost
        // TODO add your handling code here:
         if (jComboBox2.getSelectedIndex()==1){  //international
            PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
            Phonenumber.PhoneNumber phoneNumber;
        try {
            phoneNumber = phoneUtil.parse(jFormattedTextField2.getText(), "");
            if (!phoneUtil.isValidNumber(phoneNumber)){
                jLabel17.setText("Le numéro n'est pas valide");
                jLabel17.setForeground(Color.red);                                             // set color to red 
            }
            
            String formatted = phoneUtil.format(phoneNumber, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL);
            jFormattedTextField2.setDocument(new javax.swing.text.PlainDocument());
            jFormattedTextField2.setText(formatted);
        } catch (NumberParseException ex) {
            jLabel17.setText("Le numéro n'est pas valide");
            jLabel17.setForeground(Color.red); 
            Logger.getLogger(Adhesion_enfant.class.getName()).log(Level.SEVERE, null, ex);
        }

            
        }
    }//GEN-LAST:event_jFormattedTextField2FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
       
       String number=NumberFormat.getNumberInstance(Locale.FRANCE).format(Double.parseDouble(jTextField6.getText()));
       number = number.replace('\u00a0', ' ');
        System.out.println(number+"nombre");
        jTextField6.setText(number);
//        System.out.println("number"+NumberFormat.getNumberInstance(Locale.FRANCE).format(Double.parseDouble(jTextField6.getText())));
    }//GEN-LAST:event_jTextField6FocusLost

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
         // TODO add your handling code here:
         if (jComboBox1.getSelectedIndex()==0){
            jFormattedTextField4.setText("");
            jFormattedTextField4.setEnabled(false);
           
            jFormattedTextField3.setEnabled(true);
            jFormattedTextField3.setText("");
            jTextField8.setEnabled(true);
            demoDateField3.setDate(null);
            demoDateField3.setEnabled(false);
            demoDateField2.setDate(null);
            demoDateField2.setEnabled(true);
        } else if (jComboBox1.getSelectedIndex()==1){
             jFormattedTextField3.setText("");
             jFormattedTextField3.setEnabled(false);
             jFormattedTextField4.setEnabled(true);
             jFormattedTextField4.setText("");
             jTextField8.setEnabled(false);
             demoDateField2.setDate(null);
             demoDateField2.setEnabled(false);
             demoDateField3.setDate(null);
             demoDateField3.setEnabled(true);
        } else {
            jFormattedTextField3.setEnabled(true);
            jFormattedTextField3.setText("");
            jFormattedTextField4.setEnabled(true);
            jFormattedTextField4.setText("");
            jTextField8.setEnabled(true);
             demoDateField2.setDate(null);
             demoDateField2.setEnabled(true);
             demoDateField3.setDate(null);
             demoDateField3.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adhesion_persmor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adhesion_persmor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adhesion_persmor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adhesion_persmor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adhesion_persmor(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jp.samples.comp.calendarnew.DemoDateField demoDateField1;
    private com.jp.samples.comp.calendarnew.DemoDateField demoDateField2;
    private com.jp.samples.comp.calendarnew.DemoDateField demoDateField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
