/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nehemie_mutuelle;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arnowod
 */
public class Modifytontsupp extends javax.swing.JFrame {
    private String carnetlist;
    private int id;
    private String type;
    private Connection connect;
    private Object stmt;

    /**
     * Creates new form Modifytontsupp
     */
    public Modifytontsupp() {
        initComponents();
    }
    
    public Modifytontsupp(String carnetlist) {
        this.carnetlist= carnetlist;
         
        initComponents();
        this.setTitle("Modification du numero de carnet");
    }
     
     

    private boolean verifynumcarn(String tomatch) throws SQLException {    
        String sql0="SELECT Num_carnet FROM Profil_adulte WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_adulte WHERE Type_adhesion='"+"Epargne & tontine"+"'" + " UNION " +"SELECT Num_carnet FROM Profil_enfant WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_enfant WHERE Type_adhesion='"+"Epargne et tontine"+"'" + " UNION "+ "SELECT Num_carnet FROM Profil_persmorale WHERE Type_adhesion='"+"Tontine"+"' UNION SELECT RIGHT(Num_carnet,4) FROM Profil_persmorale WHERE Type_adhesion='"+"Epargne et tontine"+"' UNION SELECT numcarnettont FROM tontinesupp;";
        connect=Connect.ConnectDb();
        Statement stmt = null;
        ResultSet rs = null;
 
            
        try {
            stmt= connect.createStatement();
            rs=stmt.executeQuery(sql0);
        // compare tontine
            while (rs.next()) {
                if(tomatch.equalsIgnoreCase(rs.getString(1))) return true;
            }} catch (SQLException ex) {
                  Logger.getLogger(Adhesion_adulte.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        // connect.close();
        stmt.close();
        rs.close();
        
        return false;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        String[] values = carnetlist.split(",");
        jComboBox1 = new javax.swing.JComboBox(values);
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ancien numero");

        jLabel2.setText("Nouveau numero");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField1)
                            .addComponent(jComboBox1, 0, 163, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String numcarnetomatch = ((String) jComboBox1.getSelectedItem()).trim();
        try {
            if (numcarnetomatch.equalsIgnoreCase(jFormattedTextField1.getSelectedText())) 
                 JOptionPane.showMessageDialog(this, "Veuillez entrer un autre numéro que le numéro à changer");
            else if (verifynumcarn(numcarnetomatch) == true)
                JOptionPane.showMessageDialog(this, "Ce numéro de carnet est déjà");
            else  {
                
                //Mofications
                String sql="UPDATE tontinesupp SET numcarnettont='"+Double.valueOf(jFormattedTextField1.getSelectedText().trim())+"'WHERE iduser='"+id+"' AND typeuser='"+type+"'";
                String sql2="UPDATE enrtontinesupp SET numcarnet='"+Double.valueOf(jFormattedTextField1.getSelectedText().trim())+"'WHERE numcarnet='"+numcarnetomatch+"'";

                connect = Connect.ConnectDb();
                Statement stmt=null;
                Boolean success = true;
              try {
                 stmt = connect.createStatement();
                 stmt.executeUpdate(sql);
                 stmt.executeUpdate(sql2);
             
                 
              } catch (SQLException ex) {
                 success = false; 
                 Logger.getLogger(CreditLibre.class.getName()).log(Level.SEVERE, null, ex);

              }
             
             
              if (success) JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
              else JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement");
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Modifytontsupp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (connect !=null) try {
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(Modifytontsupp.class.getName()).log(Level.SEVERE, null, ex);
        }
       // if (stmt !=null) stmt.close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifytontsupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifytontsupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifytontsupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifytontsupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifytontsupp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
