/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nehemie_mutuelle.loan;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.time.DateUtils;

/**
 *
 * @author ucao
 */
public class CreditPanelManuel2 extends javax.swing.JPanel {

    /**
     * Creates new form CreditPanel0
     */
    public CreditPanelManuel2() {
        initComponents();
    }
    
    public class DateCellRenderer extends DefaultTableCellRenderer {
        public DateCellRenderer() {
            super();
        }

        @Override
        public void setValue(final Object value) {
            final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            String strValue = "";
            if(value != null && value instanceof Date){
               strValue = sdf.format(value);
            }
            super.setText(strValue);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(162, 161, 161));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                    Nouveau dossier de crédit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tableau d'amortissement manuel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Date", "Capital", "Intérêts", "Total"
            }
        ));
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new DateCellRenderer());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void fillTable(Date firstdate, int nbPeriodes, String freq, int nbjours){
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
        }
        
        if (freq.equalsIgnoreCase("mensuel")) {
            Date mensdat= firstdate;
        for (int i=0; i<nbPeriodes; i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] {new Integer(i+1) , mensdat, null,null, null });
           // jTable1.setValueAt(new Integer(i), i, 0);
            //jTable1.setValueAt(mensdat, i, 1);
            mensdat = DateUtils.addMonths(mensdat, 1);
        }
        } else if (freq.equalsIgnoreCase("trimestriel")) {
            Date trimdat= firstdate;
        for (int i=0; i<nbPeriodes; i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] {new Integer(i+1) , trimdat, null,null, null });
          //  jTable1.setValueAt(new Integer(i), i, 0);
          //  jTable1.setValueAt(trimdat, i, 1);
            trimdat = DateUtils.addMonths(trimdat, 3);
        }
            
        } else if (freq.equalsIgnoreCase("périodique")) {
    
            Date perioddat= firstdate;
        for (int i=0; i<nbPeriodes; i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] {new Integer(i+1) , perioddat, null,null, null });
            //jTable1.setValueAt(new Integer(i), i, 0);
            //jTable1.setValueAt(perioddat, i, 1);
            perioddat = DateUtils.addDays(perioddat, nbjours);
        }
            
        }
       // jTable1.setValueAt(new Integer("1"), 0, 0);
       // jTable1.setValueAt(new Date(), 0, 1);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
